//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public int DocumentTypeID { get; set; }
        public string DocumentTypeCode { get; set; }
        public string DocumentTypeName { get; set; }
        public Nullable<int> DocumentCategoryID { get; set; }
        public Nullable<bool> Digitalallowed { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> ToFollow { get; set; }
        public string FollowupTypeCode { get; set; }
        public string SessionYear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SchoolID { get; set; }
        public string GroupID { get; set; }
        public bool ISDeleted { get; set; }
    }
}
